spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-server-demo
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: default-route
          uri: http://localhost:8082
          predicates:
            - Path=/**

  main:
    web-application-type: reactive

server:
  port: 8001